name: Auto Visit Website

on:
  schedule:
    # Schedule it to run every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
      - name: Visit Website
        run: |
          curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" https://plant-a-base.free.nf/
